<!-- JS here -->
<script src="{{ asset('clentac/assets/js/vendor/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('clentac/assets/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('clentac/assets/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('clentac/assets/js/jquery.odometer.min.js') }}"></script>
<script src="{{ asset('clentac/assets/js/BeerSlider.js') }}"></script>
<script src="{{ asset('clentac/assets/js/jquery.appear.js') }}"></script>
<script src="{{ asset('clentac/assets/js/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('clentac/assets/js/jarallax.min.js') }}"></script>
<script src="{{ asset('clentac/assets/js/slick.min.js') }}"></script>
<script src="{{ asset('clentac/assets/js/gsap.js') }}"></script>
<script src="{{ asset('clentac/assets/js/ScrollTrigger.js') }}"></script>
<script src="{{ asset('clentac/assets/js/SplitText.js') }}"></script>
<script src="{{ asset('clentac/assets/js/gsap-animation.js') }}"></script>
<script src="{{ asset('clentac/assets/js/tg-cursor.min.js') }}"></script>
<script src="{{ asset('clentac/assets/js/wow.min.js') }}"></script>
<script src="{{ asset('clentac/assets/js/aos.js') }}"></script>
<script src="{{ asset('clentac/assets/js/main.js') }}"></script>
@yield('js')
